using System.Reflection;
[assembly: AssemblyTitle("Asceils")]
[assembly: AssemblyDescription("Image to ASCII converter")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Asceils")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.19.909.2150")]
